version: '3.8'

services:
  elif-postgres:
    image: postgres:16.1
    ports:
      - '${POSTGRES_PORT}:5432'
    environment:
      POSTGRES_USER: '${POSTGRES_USER:-user}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD:-password}'
      POSTGRES_DB: '${POSTGRES_DB:-elif}'
    volumes:
      - elif-api-db:/var/lib/postgresql/elif




volumes:
  elif-api-db: